"""
TerraLedger DDS Generator
--------------------------
Generates EU Deforestation Regulation (EUDR) compliant
Due Diligence Statements as PDF documents.

Based on the official EUDR DDS format specified in
EU Regulation 2023/1115 and the Commission's EUDR Information System.
"""

import io
import qrcode
from datetime import datetime
from typing import List
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT


TERRA_GREEN = colors.HexColor("#0F6E56")
TERRA_LIGHT = colors.HexColor("#E1F5EE")
TERRA_GRAY = colors.HexColor("#5F5E5A")
TERRA_DARK = colors.HexColor("#2C2C2A")
WHITE = colors.white
RED = colors.HexColor("#993C1D")
AMBER = colors.HexColor("#854F0B")


def _make_qr(data: str) -> io.BytesIO:
    qr = qrcode.QRCode(version=2, box_size=4, border=2)
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf


def generate_dds(
    batch_code: str,
    commodity: str,
    quantity_kg: float,
    harvest_date: datetime,
    destination_country: str,
    operator_name: str,
    operator_country: str,
    parcels: List[dict],  # List of {name, country, lat, lon, risk_level, score, compliant}
    custody_events: List[dict],  # List of {event_type, timestamp, location, actor}
    statement_date: datetime = None,
    dds_reference: str = None,
) -> bytes:
    """
    Generate a PDF Due Diligence Statement for an EUDR batch.
    Returns raw PDF bytes.
    """
    if statement_date is None:
        statement_date = datetime.utcnow()
    if dds_reference is None:
        dds_reference = f"TL-DDS-{batch_code}-{statement_date.strftime('%Y%m%d')}"

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=20 * mm,
        rightMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("H1", parent=styles["Normal"],
                         fontSize=16, textColor=TERRA_GREEN, spaceAfter=4,
                         fontName="Helvetica-Bold")
    h2 = ParagraphStyle("H2", parent=styles["Normal"],
                         fontSize=11, textColor=TERRA_DARK, spaceBefore=10, spaceAfter=4,
                         fontName="Helvetica-Bold")
    body = ParagraphStyle("Body", parent=styles["Normal"],
                           fontSize=9, textColor=TERRA_DARK, spaceAfter=3,
                           fontName="Helvetica")
    small = ParagraphStyle("Small", parent=styles["Normal"],
                            fontSize=8, textColor=TERRA_GRAY,
                            fontName="Helvetica")
    centered = ParagraphStyle("Centered", parent=body, alignment=TA_CENTER)

    story = []

    # ── Header ────────────────────────────────────────────────────────────────
    story.append(Paragraph("TerraLedger", h1))
    story.append(Paragraph(
        "EU Deforestation Regulation (EUDR) — Due Diligence Statement",
        ParagraphStyle("Sub", parent=styles["Normal"], fontSize=12,
                       textColor=TERRA_GRAY, fontName="Helvetica")
    ))
    story.append(HRFlowable(width="100%", thickness=2, color=TERRA_GREEN, spaceAfter=8))

    # Reference + date row
    ref_data = [
        ["DDS Reference:", dds_reference, "Statement Date:", statement_date.strftime("%B %d, %Y")],
        ["Regulation:", "EU 2023/1115", "Generated By:", "TerraLedger Platform v0.1"],
    ]
    ref_table = Table(ref_data, colWidths=[35 * mm, 75 * mm, 35 * mm, 45 * mm])
    ref_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), TERRA_DARK),
        ("BACKGROUND", (0, 0), (-1, -1), TERRA_LIGHT),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [TERRA_LIGHT, WHITE]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#9FE1CB")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(ref_table)
    story.append(Spacer(1, 6 * mm))

    # ── Section 1: Operator ───────────────────────────────────────────────────
    story.append(Paragraph("1. Operator Information", h2))
    op_data = [
        ["Operator / Exporter Name:", operator_name],
        ["Country of Operation:", operator_country],
        ["Role under EUDR:", "Operator placing commodity on EU market"],
    ]
    op_table = Table(op_data, colWidths=[65 * mm, 110 * mm])
    op_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), TERRA_DARK),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F1EFE8"), WHITE]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D3D1C7")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(op_table)
    story.append(Spacer(1, 4 * mm))

    # ── Section 2: Commodity Batch ────────────────────────────────────────────
    story.append(Paragraph("2. Commodity Batch Details", h2))
    batch_data = [
        ["Batch Code:", batch_code, "Commodity:", commodity.upper()],
        ["Quantity:", f"{quantity_kg:,.1f} kg", "Harvest Date:", harvest_date.strftime("%B %d, %Y")],
        ["Destination:", destination_country, "Parcel Count:", str(len(parcels))],
    ]
    batch_table = Table(batch_data, colWidths=[35 * mm, 75 * mm, 35 * mm, 45 * mm])
    batch_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (-1, -1), TERRA_DARK),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.HexColor("#F1EFE8"), WHITE]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D3D1C7")),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(batch_table)
    story.append(Spacer(1, 4 * mm))

    # ── Section 3: Farm Parcels ───────────────────────────────────────────────
    story.append(Paragraph("3. Production Parcels — Deforestation Verification", h2))
    parcel_header = ["Parcel Name", "Location", "GPS (lat, lon)", "NDVI Score", "Risk", "Compliant"]
    parcel_rows = [parcel_header]
    for p in parcels:
        risk_color = TERRA_GREEN if p.get("risk_level") == "LOW" else (
            AMBER if p.get("risk_level") == "MEDIUM" else RED
        )
        parcel_rows.append([
            p.get("name", "—"),
            p.get("country", "—"),
            f"{p.get('lat', 0):.4f}, {p.get('lon', 0):.4f}",
            f"{p.get('deforestation_score', 0):.1f}/100",
            p.get("risk_level", "—"),
            "YES" if p.get("eudr_compliant") else "NO",
        ])

    parcel_table = Table(parcel_rows, colWidths=[40 * mm, 25 * mm, 35 * mm, 25 * mm, 20 * mm, 25 * mm])
    ts = TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), TERRA_GREEN),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F1EFE8"), WHITE]),
        ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D3D1C7")),
        ("ALIGN", (3, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ])
    for i, p in enumerate(parcels, start=1):
        compliant = p.get("eudr_compliant")
        color = TERRA_GREEN if compliant else RED
        ts.add("TEXTCOLOR", (5, i), (5, i), color)
        ts.add("FONTNAME", (5, i), (5, i), "Helvetica-Bold")
    parcel_table.setStyle(ts)
    story.append(parcel_table)

    all_compliant = all(p.get("eudr_compliant") for p in parcels)
    compliance_text = "✓ ALL PARCELS VERIFIED DEFORESTATION-FREE" if all_compliant else \
                      "⚠ ONE OR MORE PARCELS FLAGGED — REVIEW REQUIRED"
    compliance_color = TERRA_GREEN if all_compliant else RED
    story.append(Spacer(1, 3 * mm))
    story.append(Paragraph(compliance_text, ParagraphStyle(
        "Compliance", parent=styles["Normal"], fontSize=10,
        textColor=compliance_color, fontName="Helvetica-Bold", alignment=TA_CENTER
    )))
    story.append(Spacer(1, 4 * mm))

    # ── Section 4: Chain of Custody ───────────────────────────────────────────
    story.append(Paragraph("4. Chain of Custody Audit Trail", h2))
    if custody_events:
        evt_header = ["Event Type", "Timestamp", "Location", "Actor"]
        evt_rows = [evt_header]
        for e in custody_events:
            evt_rows.append([
                e.get("event_type", "—"),
                e.get("event_timestamp", datetime.utcnow()).strftime("%Y-%m-%d %H:%M") if isinstance(
                    e.get("event_timestamp"), datetime) else str(e.get("event_timestamp", "—")),
                e.get("location_name", "—"),
                e.get("actor_name", "—"),
            ])
        evt_table = Table(evt_rows, colWidths=[35 * mm, 40 * mm, 55 * mm, 45 * mm])
        evt_table.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("BACKGROUND", (0, 0), (-1, 0), TERRA_DARK),
            ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#F1EFE8"), WHITE]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.HexColor("#D3D1C7")),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(evt_table)
    else:
        story.append(Paragraph("No custody events recorded for this batch.", body))
    story.append(Spacer(1, 4 * mm))

    # ── Section 5: Due Diligence Declaration ─────────────────────────────────
    story.append(Paragraph("5. Due Diligence Declaration", h2))
    declaration = (
        f"I, the undersigned operator, {operator_name}, hereby declare that, "
        f"to the best of my knowledge and belief, the {commodity.lower()} covered by "
        f"this Due Diligence Statement (Reference: {dds_reference}) is deforestation-free "
        f"within the meaning of Article 3 of EU Regulation 2023/1115. "
        f"All production parcels listed in Section 3 have been verified using satellite-based "
        f"geospatial analysis and show no evidence of deforestation or forest degradation "
        f"after December 31, 2020. This statement has been generated by the TerraLedger "
        f"platform and is backed by an immutable audit trail."
    )
    story.append(Paragraph(declaration, body))
    story.append(Spacer(1, 8 * mm))

    # Signature block
    sig_data = [
        [Paragraph("Operator Signature / Stamp:", ParagraphStyle("SigL", parent=body, fontName="Helvetica-Bold")),
         Paragraph("TerraLedger Verification QR:", ParagraphStyle("SigR", parent=body, fontName="Helvetica-Bold"))],
        ["", ""],
        [Paragraph(f"Name: {operator_name}", body), ""],
        [Paragraph(f"Date: {statement_date.strftime('%B %d, %Y')}", body), ""],
    ]

    from reportlab.platypus import Image as RLImage
    qr_buf = _make_qr(f"TERRALEDGER:{dds_reference}:{batch_code}")
    qr_img = RLImage(qr_buf, width=25 * mm, height=25 * mm)
    sig_data[1][1] = qr_img

    sig_table = Table(sig_data, colWidths=[90 * mm, 85 * mm])
    sig_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 2), (0, 2), 0.5, TERRA_GRAY),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(sig_table)

    # ── Footer ────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 4 * mm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=TERRA_GRAY, spaceAfter=3))
    story.append(Paragraph(
        f"Generated by TerraLedger • {dds_reference} • "
        f"This document constitutes a Due Diligence Statement under EU Regulation 2023/1115. "
        f"Satellite data: Sentinel-2 MSI (ESA Copernicus). "
        f"For verification: https://terraledger.io/verify/{dds_reference}",
        small
    ))

    doc.build(story)
    return buf.getvalue()
